<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

## 1 Subsetting: Indexing and Slicing

### 1.1 Indexing & Slicing 1D (Lists & Arrays)

In [2]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

x = np_array

In [4]:
x[5]                       # Selects index 5

'f6'

In [5]:
x[-1]                      # Selects index -1, i.e. the last element

'j10'

In [7]:
x[2:5]                     # This gives index 2 to index 5-1=4. In general, for a:b, the selected index is from a to b-1.

array(['c3', 'd4', 'e5'], dtype='<U3')

In [12]:
x[2:8:3]                   # Selects elements within 2 to 7 at intervals of 3, i.e., index 2 and 5.
                           # In general, for a:b:c, starting from a, elements are selected at intervals of c, 
                           # until index b-1 is reached.

array(['c3', 'f6'], dtype='<U3')

In [10]:
print(x[3:])               # "a:" indicates selection from index a to the end of the list.
print(x[:8])               # ":b" indicates selection from the start of the list to index b-1

['d4' 'e5' 'f6' 'g7' 'h8' 'i9' 'j10']
['a1' 'b2' 'c3' 'd4' 'e5' 'f6' 'g7' 'h8']


In [15]:
x[5:2:-1]                  # -1 reverses the selection process, from index 5 to 3. (i.e., b:a:-1, index b to a+1 is selected)

array(['f6', 'e5', 'd4'], dtype='<U3')

In [16]:
print(x[::-1])             # List is reversed

['j10' 'i9' 'h8' 'g7' 'f6' 'e5' 'd4' 'c3' 'b2' 'a1']


### 1.2 Subsetting by masking (Arrays only)

In [24]:
np_array=np.array([1,2,3,4,5,6,7,8,9,10])
np_mask=np_array > 3                      
np_array[np_mask]

array([ 4,  5,  6,  7,  8,  9, 10])

In [25]:
np_array[np_array>3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [27]:
np_array[~(np_array>3)]                       # ~ (NOT) excludes values that satisfy the argument

array([1, 2, 3])

In [29]:
np_array[(np_array>3) & (np_array<8)]         # & (AND) selects values that satisfy both arguments

array([4, 5, 6, 7])

In [30]:
np_array[(np_array>3)|(np_array<8)]           # | (OR) selects values that satisfy either argument

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### 1.3 Indexing & Slicing 2D Lists

In [32]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

In [35]:
py_list_2d[3]                              # Index 3 (4th position)

[4, 'D']

In [36]:
py_list_2d[3][1]                           # Second element at index 3

'D'

In [38]:
py_list_2d[3:]                             # All indexes including and after index 3.

[[4, 'D'], [5, 'E'], [6, 'F'], [7, 'G'], [8, 'H'], [9, 'I'], [10, 'J']]

In [39]:
py_list_2d[:5]                             # All indexes before index 5.

[[1, 'A'], [2, 'B'], [3, 'C'], [4, 'D'], [5, 'E']]

In [67]:
py_list_2d[3:6][2]                          # DOES NOT show the a list of the first element from index 3 to 5.
                                            # Instead, it shows the index that is two positions ahead of index 3 (i.e., index 5)

[6, 'F']

### 1.4 Indexing & Slicing 2D Arrays

In [56]:
np_array_2d = np.array([[1, "A"], [2, "B"], [3, "C"], [4, "D"],
                        [5, "E"], [6, "F"], [7, "G"], [8, "H"],
                        [9, "I"], [10, "J"]])

In [61]:
np_array_2d[6]                            # Shows index 6 (position 7)

array(['7', 'G'], dtype='<U11')

In [59]:
np_array_2d[3][1]                         # Shows the second element of index 3 (position 4)                 

'D'

In [60]:
np_array_2d[:3]                           # Shows index 0 to 2 (positions 1 to 3)

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C']], dtype='<U11')

In [65]:
np_array_2d[3:6, 0]                      # Shows the first element of index 3 to 5 
                                         # (note that a comma is used, instead of two sets of square brackets)

array(['4', '5', '6'], dtype='<U11')

In [68]:
np_array_2d[:,0]                         # Shows all elements.

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U11')

### 1.5 Growing lists

In [83]:
x=[1]*5                                  # Duplicates initial list 5 times.

x

[1, 1, 1, 1, 1]

In [82]:
x = [1]
x += [2]
x += [3]
x += [4]

x

[1, 2, 3, 4]

In [81]:
x = [1]
x += [2,3,4]

x

[1, 2, 3, 4]

In [84]:
x = [1]
x = [2,3,4] + x                          # Second list is added before the initial list.

x

[2, 3, 4, 1]

In [90]:
x = [1]
x.append(2)
x.append(3)                             # append() adds to the end of the list; accepts only one argument at a time.

x

[1, 2, 3]

## 2 Some loose ends

### 2.1 Tuples

In [93]:
a=(1,2,3)                              # Tuples cannot be changed after creation
print(a[0])

1


In [95]:
a[0] += 10 

TypeError: 'tuple' object does not support item assignment

### 2.2 Be VERY careful when copying

In [111]:
# Use the copy() function when copying lists, 
# such as they remain as independent lists, 
# which can be altered without affecting other lists

x = [1,2,3]
y = x.copy()
z = y.copy()

y.append(4)
z.append(0)

print(x)
print(y)
print(z)

[1, 2, 3]
[1, 2, 3, 4]
[1, 2, 3, 0]


## Exercise 1 :  Total recall?

|**Term**|**Brief Description**|
|:--|:--|
|Subsetting|Selecting elements from a list|
|Indexing|Selecting a single element|
|Slcing|Selecting a range of element|
|Masking|Using True/False boolean to mask certain elements. Only elements marked as "True" remain shown.|

## Exercise 2 :  Show me the ‘odd’ letters

In [112]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

In [155]:
np_mask = np_array_2d[::,0].astype(int)%2 == 1                 

print(np_array_2d[np_mask][::,1])

# Process:
# np_mask is created by selecting all first elements that are odd, followed by converting them into integer type,
# then using modulo division to give remainders of 0 for even numbers, and 1 for odd numbers, and finally,
# masking by checking if each element is equal to 1. Only odd numbers will be selected for the mask.


['A' 'C' 'E' 'G' 'I']
