<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

## 1 Lists, Arrays & Dictionaries

### 1.1 Let’s compare

In [1]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

# A Python List stores multiple items in a single variable.

In [2]:
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

# NumPy Array is similar to Python List, except that the NumPy package is used.

In [3]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

# Dictionary stores information as keys and their associated value, separated by a colon.

### 1.2 Accessing data from a list (or array)

In [10]:
print(np_super_names[2])
print(np_real_names[1])

# Each item on the list is tied to a index, starting from 0. 
# Using indexing without any item tied to them (above 2, for a 3-item list) will return an error.

Doctor Strange
Tony Stark


In [14]:
print(np_super_names[-1])

# Negative indexing ties items in reverse order to the index, starting with the last item tied to -1.
# Similar to Forward indexing, a 3-item list only uses index -1 to -3.

Doctor Strange


### 1.3 Accessing data from a dictionary

In [17]:
print(superhero_info["Tony Stark"])

# Prints out associated value tied to this key in the set dictionary.

Iron Man


In [18]:
superhero_info.keys()

dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])

In [20]:
superhero_info.values()

dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])

### 1.4 Higher dimensional lists

In [25]:
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]

# Sets up a 2-column list/array, with each row being grouped together.

print(py_superhero_info[0])

['Natasha Romanoff', 'Black Widow']


## 2 Lists vs. Arrays

### 2.1 Size

In [31]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)

In [35]:
len(py_list_2d)

10

In [36]:
len(np_array_2d)

10

In [39]:
np_array_2d.shape     # shape is not a function, but a NumPy attribute/property of the array, hence there are no brackets.

(10, 2)

In [41]:
py_list_2d.shape      # Python lists do not have the shape attribute.

AttributeError: 'list' object has no attribute 'shape'

### 2.2 Arrays are fussy about type

In [40]:
py_list = [1, 1.5, "A"]

np.array(py_list)         # NumPy tolerates only one data type (float, int, str) in the array

array(['1', '1.5', 'A'], dtype='<U32')

### 2.3 Adding a number

In [67]:
py_list = [1,2,3,4,5]
np_array = np.array(py_list)  # Reuses py_list to create a new NumPy array.

In [68]:
np_array_A = np.array([1,2,3,4,5])

py_list_A = np_array_A.tolist()  # tolist() function converts array to list.

py_list_A*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [43]:
py_list + 10   # Adding numbers to the items in the list does not work in Python list

TypeError: can only concatenate list (not "int") to list

In [44]:
np_array + 10  # 10 is added to each item in the array.

array([11, 12, 13, 14, 15])

### 2.4 Adding another list

In [45]:
py_list_1 = [1,2,3,4,5]
py_list_2 = [10,20,30,40,50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

In [46]:
py_list_1 + py_list_2    # Addition merges two Python lists

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [47]:
np_array_1 + np_array_2  # The values of each pair of items found in the same index in both lists are added together.

array([11, 22, 33, 44, 55])

### 2.5 Multiplying by a Number

In [49]:
py_list*2                # Multiplication duplicates the Python List          

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [50]:
np_array*2               # All numerical values in the list are multiplied by 2.

array([ 2,  4,  6,  8, 10])

### 2.6 Squaring

In [51]:
py_list**2               # Exponents do not work with Python lists.

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [52]:
np_array**2              # The numerical values in the list are squared.

array([ 1,  4,  9, 16, 25])

### 2.7 Asking questions

In [70]:
py_list == py_list_1    # Checks whether the two lists are exactly the same.

True

In [71]:
py_list == 3            # Since py_list is not the same as the value 3

False

In [73]:
np_array == 3           # Checks each item to see if any match the value given.

array([False, False,  True, False, False])

In [74]:
py_list > 3             # Does not work

TypeError: '>' not supported between instances of 'list' and 'int'

In [75]:
np_array > 3            # Checking inequalities work in arrays.

array([False, False, False,  True,  True])

### 2.8 Mathematics

In [80]:
print(sum(py_list), min(py_list), max(py_list))  # sum(), min() and max () are base functions. They do not work using the dot.

15 1 5


In [82]:
print(np_array.sum(),np_array.min(),np_array.max(), np_array.mean())  # The dot is used for array. NumPy also has the mean().

15 1 5 3.0


## Exercise 1 :  Total recall?

Similarities

- Both lists and arrays are ordered, and thus indexing can be used.
- Items can be added and removed from lists and arrays after creation.

Differences

- NumPy arrays directly support mathematical operations, lists do not.
- When asking questions, the entire Python list is checked as one, while individual items within the array is checked.

What is a Dictionary?

- A collection of items consisting of keys and their associated values.

## Exercise 2 :  Index me

In [83]:
py_list = ["a1", "b2", "c3", "d4", "e5", "f6", "g7", "h8", "i9", "j10"]
print(py_list[0])   # Prints 'a1'
print(py_list[2])   # Prints 'c3'
print(py_list[4])   # Prints 'e5'
print(py_list[6])   # Prints 'g7'
print(py_list[8])   # Prints 'i9'

a1
c3
e5
g7
i9


## Exercise 3 :  Capitalise Heros

In [91]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"}

superhero_info['Tony Stark'] = superhero_info['Tony Stark'].upper()
superhero_info['Natasha Romanoff'] = superhero_info['Natasha Romanoff'].upper()
superhero_info['Stephen Strange'] = superhero_info['Stephen Strange'].upper()

print(superhero_info['Tony Stark'],",", superhero_info['Natasha Romanoff'],",",superhero_info['Stephen Strange'])

IRON MAN , BLACK WIDOW , DOCTOR STRANGE


## Exercise 4 :  How many ones

In [96]:
numbers=[45, 60, 1, 30, 96, 1, 96, 57, 16, 1,
        99, 62, 86, 43, 42, 60, 59, 1, 1, 35,
        83, 47, 34, 28, 68, 23, 22, 92, 1, 79,
        1, 29, 94, 72, 46, 47, 1, 74, 32, 20,
        8, 37, 35, 1, 89, 29, 86, 19, 43, 61]

np_numbers = np.array(numbers)
np_count = np.array(np_numbers == 1)
np_count.sum()

9

In [97]:
print(numbers.count(1))

9
